### ISSUE TITLE
Module reported error during install: 1293 Incorrect table definition

### ISSUE THREAD

**Issue by digitalbricks** [rockettpw/jumplinks#21] opened 2017-09-29 13:46 UTC
#### Version Info:

- ProcessWire: 3.0.62
- Jumplinks: 1.5.48
- PHP: 7.0
- MySQL: 5.5

#### Details:

During installation of the module, ProcessWire reports the following error:

> Module reported error during install (ProcessJumplinks): SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

and also

> Failed to init module: ProcessJumplinks - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db692315716.process_jumplinks' doesn't exist

Therefore the module cannot be used after installation. 
I previously used the module on other sites (on other servers with other PW versions) and it always worked fine. But this time – in the given environment – there is this error mentioned above.

**Comment by mikerockett** [comment] 2017-09-29 14:32
Duplicate of #18. Is there any chance you can upgrade to at least MySQL 5.6.5?

**Comment by digitalbricks** [comment] 2017-09-29 14:42
Unfortunately no :-(
It's a shared server from 1&1 and currently all new databases runnning MySQL 5.5

Source: [https://community.1und1.de/php-composer-bei-1und1-verwenden/#comment-145682](https://community.1und1.de/php-composer-bei-1und1-verwenden/#comment-145682)

> Wir bieten im Shared Hosting nur MySQL 5.5 an.

**Comment by mikerockett** [comment] 2017-09-29 14:51
That is terrible of them, seriously. 5.6 has been around for a considerable amount of time, and it is very stable, so I don't see why they're not doing this. I have never heard good stories come from 1and1.

That aside, I will fix the issue in a few hours.

**Comment by mikerockett** [comment] 2017-09-29 16:05
Please see above commit on the dev branch. You'll need to install using this ZIP file through the module installer: https://github.com/rockettpw/jumplinks/archive/dev.zip

Let me know if it works, please.

**Comment by digitalbricks** [comment] 2017-09-29 16:39
@mikerockett Just tested aaaand: It works great! Thank you very much – this saved my day!

**Comment by mikerockett** [comment] 2017-09-29 16:46
I'm actually being silly here... MySQL 5.7 does not allow zero dates without the definition being set to `NULL`. So I'll need to add that in as well before I fast-forward this to master.

**Comment by mikerockett** [comment] 2017-09-29 16:58
I've made the commit - please check again to make sure it works on your end.

Truly hope I'm not breaking anything for those with 5.6...

**Comment by digitalbricks** [comment] 2017-09-29 17:25
You did the commit on the dev branch, right?
I uninstalled and deleted the module and did a new install from https://github.com/rockettpw/jumplinks/archive/dev.zip. Ran flawless! Than i imported my redirects CSV and all redirects work properly. Can't see any error, looks good!

BTW: How do i update the module once that changes found their way to the master branch?

**Comment by mikerockett** [comment] 2017-09-29 17:29
Yep, with these kinds of possible breaking changes on some setups, I had to create a dev branch for these changes. If everything looks stable, then I will commit to master.

Glad to know it works on your end. Going to leave it in dev for the time being - perhaps more people could test it out to make sure nothing breaks. This MySQL timestamp issue has been doing the rounds for a while.

Regarding the update: When it makes its way into master, the version will be bumped to 1.5.49. If you're using the `ProcessWireUpgrade`, it will automatically pick it up. Otherwise, you can just keep the module installed, go to Modules > New > Install and enter the location of the master ZIP. But you won't need to do any of that as it does work on your end - truthfully, it doesn't matter if you're using the dev branch or the master.

**Comment by digitalbricks** [comment] 2017-09-29 17:32
@mikerockett You are great, thank you very much!

**Closed** 2017-10-23 18:17 UTC
Labels: Compat, Duplicate
